# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Submodule Sync
        # You may pin to the exact commit or the version.
        # uses: mheap/submodule-sync-action@641989c2269722db02f0aed1daad7fe8e3fb7ee8
        uses: mheap/submodule-sync-action@v1
        with:
          # The GitHub API token to use
          token:  ${{ github.token }} # optional, default is ${{ github.token }}
          # The path in the repo to update
          path: https://github.com/wateraccounting/WAPOROCW.git
          # The branch name to check for updates in the remote repo
          ref: master
          # The name of the branch to use when creating a pull request
          pr_branch: main
          # The name of the branch that the PR should be raised against
          target_branch: main
